# Generated by Django 3.2.7 on 2021-09-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
